[package]
name = "ac-ffmpeg-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ac-ffmpeg = "0.18.1"
anyhow = "1.0.86"
